services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5435:5432"

  app:
    build:
      context: .
      dockerfile: db_test.dockerfile
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      HOST: db
      PORT: 5432
    depends_on:
      - db